Affiliates and affiliate users
Stranger6667/pyoffers pull request #55
Opened 2018-02-16 10:27 UTC by iamanikeev

2018-02-16 14:48 UTC, Stranger6667 commented on tests/models/test_affiliate.py
> +CASSETTE_NAME = 'affiliate'
Please, add extra empty line above

2018-02-16 15:45 UTC, iamanikeev commented on tests/models/test_affiliate.py
> +CASSETTE_NAME = 'affiliate'
Done

2018-02-20 09:49 UTC, Stranger6667 requested changes
Please, rebase and add documentation notes for the new model

2018-02-20 09:51 UTC, Stranger6667 commented
Also, fix isort build, which will fail I suppose (because of a single empty line after the imports in affiliate.py)

2018-02-20 10:02 UTC, Stranger6667 requested changes
I've added my comments on the changes

2018-02-20 10:02 UTC, Stranger6667 commented on pyoffers/models/affiliate.py
> +    def affiliate_user(self):
Please, rename ``affiliate_user`` -> ``user``. I think, that this repetition will only decrease readability

2018-02-20 10:02 UTC, Stranger6667 commented on pyoffers/models/affiliate.py
> +        return RelatedUserManager(api=self._manager.api, base_manager_class=AffiliateUserManager, id=self.id).get()
AffiliateUser should be initialized here without extra code in ``__getattribute__`` and RelatedManager

2018-02-20 10:02 UTC, Stranger6667 commented on pyoffers/models/core.py
> +class RelatedManager:
Could you, please, move this class to its initial place?

2018-02-20 10:02 UTC, Stranger6667 commented on pyoffers/models/affiliate.py
> +class RelatedUserManager(RelatedManager):
Probably, this class is redundant.

2018-02-20 10:02 UTC, Stranger6667 commented on pyoffers/models/affiliate.py
> +    def create(self, create_user=True, **kwargs):
Let's simplify the interface and remove creating of AffiliateUser. It still will be possible via ``api.affiliate_users.create``

2018-02-20 14:44 UTC, Stranger6667 commented on pyoffers/models/affiliate.py
> +        Creates an affiliate and corresponding affiliate user (if ``create_user`` is set)
Docstring is obsolete

2018-02-20 14:44 UTC, Stranger6667 commented on pyoffers/models/affiliate.py
> +        Creates an affiliate and corresponding affiliate user (if ``create_user`` is set)
This docstring is obsolete as well

2018-02-20 14:44 UTC, Stranger6667 commented on pyoffers/models/core.py
> +        return self.base_manager.find_all(**kwargs)
Missing newline

2018-02-20 14:51 UTC, Stranger6667 approved these changes

2018-02-20 14:55 UTC, merged